kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deployment-scaler-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: deployment-scaler
  namespace: default
roleRef:
  kind: Role
  name: deployment-scaler-role
  apiGroup: rbac.authorization.k8s.io
